version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
 
    steps:
      - checkout

      - run:
         name: build dependences
         command: bundle install

      - run:
         name: Compilar el sitio
         command: bundle exec jekyll build

      - run:
         print: Print la fecha actual
         command: date
